on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 1 * *'

name: lychee link check

concurrency:
  group: lychee-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config .lychee.toml
            --no-progress
            '*.md'
            'vignettes/*.Rmd'
            'DESCRIPTION'
          fail: false
